name: Production Deploy
on:
  push:
    branches:
      - main
jobs:
  web-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./
    steps:
      - name: Get latest code
        uses: actions/checkout@v2.3.4
        with:
          submodules: true # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: npm install
        run: npm install

      - name: tailwindcss
        run: npx tailwindcss -i ./assets/css/main.css -o ./assets/css/style.css

      - name: Build minified
        run: hugo --environment production --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          deploy_key: ${{ secrets.DEPLOY_KEY }}
          publish_dir: ./public
          external_repository: zhannicholas/zhannicholas.github.io
          publish_branch: main  # default: gh-pages
